#!/usr/bin/env perl

my $user=$ARGV[0];
my $key=$ARGV[1];

my ($login,$pass,$uid,$gid);

$user =~ y/ |;|\||<|>|&/_/;

if($key =~ /BEGIN/){
  print "Converting to openssh format...\n";
  my $tmpname="/tmp/$$-delkey";
  open(F,">$tmpname") or die "Cannot create $tmpname ($?)\n";
  print F $key;
  close F;
  my $newkey=`ssh-keygen -i -f '$tmpname' && rm '$tmpname'`;
  chomp($newkey);
  $key=$newkey if $newkey ne ''; 
}
    
print "Adding key for ${user}!\n";

unless(open(F, "</home/$user/.ssh/authorized_keys")){
  print "No authorized_keys for $user! Creating new.\n";
  open(F,"</dev/null");
}

while(<F>){
  chomp;
  push @keys, $_;
}
close F;

unless(open(F, ">/home/$user/.ssh/authorized_keys")){
  print "Oooops! Cannot write to /home/$user/.ssh/authorized_keys. ($?)\n";
  exit 1;
}

($login,$pass,$uid,$gid) = getpwnam($user);
chown $uid, $gid, "/home/$user/.ssh/authorized_keys";
chmod 0600, "/home/$user/.ssh/authorized_keys";

foreach $i (@keys){
  print F "$i\n";
}
print F "$key\n";
close F;

print "Key added\n";

