#!/bin/bash

if [ $(getent passwd $1) ]; then
  echo "User $1 already exists. Ignore..."
  exit 0
fi

if [ $(getent group $2) ]; then
  true
else
  groupadd $2
fi

useradd -m -g "$2" "$1" && su -c "cd '/home/$1'; echo '' | ssh-keygen -q -t rsa -N '' && cat .ssh/id_rsa.pub >> .ssh/authorized_keys" "$1"

