source 'https://rubygems.org'
  
gem 'sinatra'
gem 'activerecord'
gem 'activesupport'
gem 'slim'
gem 'pg'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'capistrano-resque'
gem 'capistrano-unicorn', :require => false
gem 'unicorn'
gem 'cocaine'
gem 'resque'
gem 'rake'
gem 'rspec'
gem 'file-tail'
